import Image from "next/image";
import "./globals.css";
import { Bellefair, Barlow_Condensed, Barlow } from "next/font/google";
import { Navbar } from "./Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const barlow_condensed = Barlow_Condensed({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-barlow-cond",
});

const bellefair = Bellefair({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-bellefair",
});

const barlow = Barlow({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-barlow",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`h-full ${bellefair.variable} ${barlow.variable} ${barlow_condensed.variable}`}
    >
      <body className={`relative h-full w-full`}>
        <nav className="px-8 absolute flex items-start pointer-events-none h-full justify-between z-10 w-full">
          <Image
            priority={true}
            className="mt-8 max-md:w-[40px] max-md:h-[40px]"
            src="/assets/shared/logo.svg"
            width={48}
            height={48}
            alt="A logo representing a star"
          />
          <Navbar />
        </nav>
        <main className="flex-grow w-full h-full">{children}</main>
      </body>
    </html>
  );
}
